using System; using Newtonsoft.Json; using Xamarin.Forms;  namespace Mafia { 	public class NightForNoMafiaViewsModel : ContentPage 	{ 		private readonly IGameService _gameService; //!! 		public int i; 		private Page _page;  		public NightForNoMafiaViewsModel(Page page, IGameService gameService) //!!
		{ 			i = 0; 			_gameService = gameService; //!! 			_gameService.OnReceive += GameService_OnReceive; //!!
		}  		private void GameService_OnReceive(object sender, Message e) //принимает данные сервера
		{ 			Device.BeginInvokeOnMainThread(async () => 				{ 					try 					{ 						if ((e.UserType == "nightkilling") && (i == 0)) 						{ 							i++; 							var json = "{\"UserRoom\":\"" + GameService.Instance._userRoom + "\"} "; // создание комнаты 							var response = await DataService.GetInstance().GetAdmin(json); 							var answer = JsonConvert.DeserializeObject<AdminModel>(response);   							GameService.Instance.GetLastKill(e.UserMessage); 							if (e.UserMessage == GameService.Instance._userName) 							{ 								var app = (App)Application.Current; // без вовзврата на  								app.MainPage = new NavigationPage(new NightResultDeadPage()); // предыдущую страницу
																																													  //}
							} 							else 							{ 								if (GameService.Instance._userName == answer.admin) 								{ 									var app = (App)Application.Current; // без вовзврата на  									app.MainPage = new NavigationPage(new NightResultAdminPage()); // предыдущую страницу
								} 								else 								{ 									var app = (App)Application.Current; // без вовзврата на  									app.MainPage = new NavigationPage(new NightResultPage()); // предыдущую страницу
								} 							} 						} 						if ((e.UserType == "gameover") && (i == 0)) 						{ 							i++; 							if (e.UserMessage == "mir") 							{ 								GameService.Instance.GetLastKill(e.UserName); 								if (e.UserName == GameService.Instance._userName) 								{ 									var app = (App)Application.Current; // без вовзврата на  									app.MainPage = new NavigationPage(new MirWinDeadPage()); // предыдущую страницу
																																														 //}
								} 								else 								{ 									var app = (App)Application.Current; // без вовзврата на  									app.MainPage = new NavigationPage(new MirWinPage()); // предыдущую страницу
								} 							} 							if (e.UserMessage == "maf") 							{ 								GameService.Instance.GetLastKill(e.UserName); 								if (e.UserName == GameService.Instance._userName) 								{ 									var app = (App)Application.Current; // без вовзврата на  									app.MainPage = new NavigationPage(new MafiaWinDeadPage()); // предыдущую страницу
								} 								else 								{ 									var app = (App)Application.Current; // без вовзврата на  									app.MainPage = new NavigationPage(new MafiaWinPage()); // предыдущую страницу
								} 							} 						} 					} 					catch (Exception k) 					{ 					} 				}); 		} 	} }    